
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_h1688fprop_fixed_channels_128x64_32x2_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_h1688fprop_fixed_channels_128x64_32x2_nhwc_align8(Manifest &manifest);
void initialize_cutlass_tensorop_h1688fprop_fixed_channels_256x64_32x2_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_h1688fprop_fixed_channels_256x64_32x2_nhwc_align8(Manifest &manifest);
void initialize_cutlass_tensorop_h1688fprop_fixed_channels_128x128_32x2_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_h1688fprop_fixed_channels_128x128_32x2_nhwc_align8(Manifest &manifest);
void initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x256_32x2_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x256_32x2_nhwc_align8(Manifest &manifest);
void initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x128_32x2_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x128_32x2_nhwc_align8(Manifest &manifest);
void initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x64_32x2_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x64_32x2_nhwc_align8(Manifest &manifest);
void initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x128_64x2_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x128_64x2_nhwc_align8(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm75_h1688fprop_fixed_channels_conv2d_operations(Manifest &manifest) {
  initialize_cutlass_tensorop_h1688fprop_fixed_channels_128x64_32x2_nhwc_align4(manifest);
  initialize_cutlass_tensorop_h1688fprop_fixed_channels_128x64_32x2_nhwc_align8(manifest);
  initialize_cutlass_tensorop_h1688fprop_fixed_channels_256x64_32x2_nhwc_align4(manifest);
  initialize_cutlass_tensorop_h1688fprop_fixed_channels_256x64_32x2_nhwc_align8(manifest);
  initialize_cutlass_tensorop_h1688fprop_fixed_channels_128x128_32x2_nhwc_align4(manifest);
  initialize_cutlass_tensorop_h1688fprop_fixed_channels_128x128_32x2_nhwc_align8(manifest);
  initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x256_32x2_nhwc_align4(manifest);
  initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x256_32x2_nhwc_align8(manifest);
  initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x128_32x2_nhwc_align4(manifest);
  initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x128_32x2_nhwc_align8(manifest);
  initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x64_32x2_nhwc_align4(manifest);
  initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x64_32x2_nhwc_align8(manifest);
  initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x128_64x2_nhwc_align4(manifest);
  initialize_cutlass_tensorop_h1688fprop_fixed_channels_64x128_64x2_nhwc_align8(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

