
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_h16816gemm_u8_f16_128x128_64x4_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_h16816gemm_u8_f16_128x128_64x3_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_h16816gemm_u8_f16_128x64_64x5_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_h16816gemm_u8_f16_128x64_64x4_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_h16816gemm_u8_f16_128x64_64x3_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_h16816gemm_u8_f16_128x32_64x9_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_h16816gemm_u8_f16_128x32_64x5_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_h16816gemm_u8_f16_128x16_64x5_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_h16816gemm_u8_f16_128x16_64x3_tn_align16(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm80_h16816gemm_u8_f16_gemm_operations(Manifest &manifest) {
  initialize_cutlass_tensorop_h16816gemm_u8_f16_128x128_64x4_tn_align16(manifest);
  initialize_cutlass_tensorop_h16816gemm_u8_f16_128x128_64x3_tn_align16(manifest);
  initialize_cutlass_tensorop_h16816gemm_u8_f16_128x64_64x5_tn_align16(manifest);
  initialize_cutlass_tensorop_h16816gemm_u8_f16_128x64_64x4_tn_align16(manifest);
  initialize_cutlass_tensorop_h16816gemm_u8_f16_128x64_64x3_tn_align16(manifest);
  initialize_cutlass_tensorop_h16816gemm_u8_f16_128x32_64x9_tn_align16(manifest);
  initialize_cutlass_tensorop_h16816gemm_u8_f16_128x32_64x5_tn_align16(manifest);
  initialize_cutlass_tensorop_h16816gemm_u8_f16_128x16_64x5_tn_align16(manifest);
  initialize_cutlass_tensorop_h16816gemm_u8_f16_128x16_64x3_tn_align16(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

