
/*
  Generated by conv2d_operation.py - Do not edit.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

#include "library_internal.h"
#include "conv2d_operation.h"

///////////////////////////////////////////////////////////////////////////////////////////////////


  // Conv2dDgrad Analytic kernel instance "cutlass_tensorop_bf16_s16816dgrad_analytic_bf16_256x64_32x4_nhwc_unity_stride_align4"
  using cutlass_tensorop_bf16_s16816dgrad_analytic_bf16_256x64_32x4_nhwc_unity_stride_align4_base =
  typename cutlass::conv::kernel::DefaultConv2dDgrad<
    cutlass::bfloat16_t,
    cutlass::layout::TensorNHWC,
    cutlass::bfloat16_t,
    cutlass::layout::TensorNHWC,
    cutlass::bfloat16_t,
    cutlass::layout::TensorNHWC,
    float,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<256, 64, 32>,
    cutlass::gemm::GemmShape<64, 64, 32 >,
    cutlass::gemm::GemmShape<16, 8, 16>,
    cutlass::epilogue::thread::LinearCombination<
      cutlass::bfloat16_t,
      4,
      float,
      float
    >,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<4>, // cutlass::gemm::threadblock::GemmSplitKIdentityThreadblockSwizzle<>,
    4,
    cutlass::arch::OpMultiplyAdd,
    cutlass::conv::IteratorAlgorithm::kAnalytic,
    cutlass::conv::StrideSupport::kUnity,
    4,
    4
  >::Kernel;

// Derived class
struct cutlass_tensorop_bf16_s16816dgrad_analytic_bf16_256x64_32x4_nhwc_unity_stride_align4 :
  public cutlass_tensorop_bf16_s16816dgrad_analytic_bf16_256x64_32x4_nhwc_unity_stride_align4_base { };

///////////////////////////////////////////////////////////////////////////////////////////////////



namespace cutlass {
namespace library {

// Initialize all instances
void initialize_cutlass_tensorop_bf16_s16816dgrad_analytic_bf16_256x64_32x4_nhwc_unity_stride_align4(Manifest &manifest) {

  using Operation_cutlass_tensorop_bf16_s16816dgrad_analytic_bf16_256x64_32x4_nhwc_unity_stride_align4 = cutlass::conv::device::ImplicitGemmConvolution<
    cutlass_tensorop_bf16_s16816dgrad_analytic_bf16_256x64_32x4_nhwc_unity_stride_align4>;

  manifest.append(new cutlass::library::Conv2dOperation<
      Operation_cutlass_tensorop_bf16_s16816dgrad_analytic_bf16_256x64_32x4_nhwc_unity_stride_align4
    >(
      "cutlass_tensorop_bf16_s16816dgrad_analytic_bf16_256x64_32x4_nhwc_unity_stride_align4"
    ));

}


///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

///////////////////////////////////////////////////////////////////////////////////////////////////

