
/*
  Generated by conv3d_operation.py - Do not edit.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

#include "library_internal.h"
#include "conv3d_operation.h"

///////////////////////////////////////////////////////////////////////////////////////////////////


  // Conv3dFprop Analytic kernel instance "cutlass_tensorop_s16816fprop3d_analytic_f16_64x128_32x6"
  using cutlass_tensorop_s16816fprop3d_analytic_f16_64x128_32x6_base =
  typename cutlass::conv::kernel::DefaultConv3dFprop<
    cutlass::half_t,
    cutlass::layout::TensorNDHWC,
    cutlass::half_t,
    cutlass::layout::TensorNDHWC,
    float,
    cutlass::layout::TensorNDHWC,
    float,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<64, 128, 32>,
    cutlass::gemm::GemmShape<32, 64, 32 >,
    cutlass::gemm::GemmShape<16, 8, 16>,
    cutlass::epilogue::thread::LinearCombination<
      float,
      4,
      float,
      float
    >,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<4>, // cutlass::gemm::threadblock::GemmSplitKIdentityThreadblockSwizzle<>,
    6,
    cutlass::arch::OpMultiplyAdd,
    cutlass::conv::IteratorAlgorithm::kAnalytic,
    cutlass::conv::StrideSupport::kStrided
  >::Kernel;

// Derived class
struct cutlass_tensorop_s16816fprop3d_analytic_f16_64x128_32x6 :
  public cutlass_tensorop_s16816fprop3d_analytic_f16_64x128_32x6_base { };

///////////////////////////////////////////////////////////////////////////////////////////////////



namespace cutlass {
namespace library {

// Initialize all instances
void initialize_cutlass_tensorop_s16816fprop3d_analytic_f16_64x128_32x6(Manifest &manifest) {

  using Operation_cutlass_tensorop_s16816fprop3d_analytic_f16_64x128_32x6 = cutlass::conv::device::ImplicitGemmConvolution<
    cutlass_tensorop_s16816fprop3d_analytic_f16_64x128_32x6>;

  manifest.append(new cutlass::library::Conv3dOperation<
      Operation_cutlass_tensorop_s16816fprop3d_analytic_f16_64x128_32x6
    >(
      "cutlass_tensorop_s16816fprop3d_analytic_f16_64x128_32x6"
    ));

}


///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

///////////////////////////////////////////////////////////////////////////////////////////////////

