
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_d884syrk_128x128_16x3_n_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_64x128_16x3_n_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_128x64_16x3_n_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_64x64_16x4_n_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_64x32_16x4_n_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_32x64_16x4_n_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_32x32_16x5_n_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_16x32_16x5_n_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_32x16_16x5_n_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_128x128_16x3_n_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_64x128_16x3_n_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_128x64_16x3_n_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_64x64_16x4_n_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_64x32_16x4_n_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_32x64_16x4_n_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_32x32_16x5_n_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_16x32_16x5_n_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_32x16_16x5_n_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_128x128_16x3_t_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_64x128_16x3_t_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_128x64_16x3_t_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_64x64_16x4_t_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_64x32_16x4_t_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_32x64_16x4_t_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_32x32_16x5_t_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_16x32_16x5_t_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_32x16_16x5_t_l_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_128x128_16x3_t_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_64x128_16x3_t_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_128x64_16x3_t_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_64x64_16x4_t_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_64x32_16x4_t_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_32x64_16x4_t_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_32x32_16x5_t_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_16x32_16x5_t_u_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884syrk_32x16_16x5_t_u_align1(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm80_d884syrk_rank_k_operations(Manifest &manifest) {
  initialize_cutlass_tensorop_d884syrk_128x128_16x3_n_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_64x128_16x3_n_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_128x64_16x3_n_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_64x64_16x4_n_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_64x32_16x4_n_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_32x64_16x4_n_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_32x32_16x5_n_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_16x32_16x5_n_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_32x16_16x5_n_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_128x128_16x3_n_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_64x128_16x3_n_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_128x64_16x3_n_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_64x64_16x4_n_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_64x32_16x4_n_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_32x64_16x4_n_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_32x32_16x5_n_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_16x32_16x5_n_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_32x16_16x5_n_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_128x128_16x3_t_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_64x128_16x3_t_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_128x64_16x3_t_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_64x64_16x4_t_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_64x32_16x4_t_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_32x64_16x4_t_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_32x32_16x5_t_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_16x32_16x5_t_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_32x16_16x5_t_l_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_128x128_16x3_t_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_64x128_16x3_t_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_128x64_16x3_t_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_64x64_16x4_t_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_64x32_16x4_t_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_32x64_16x4_t_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_32x32_16x5_t_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_16x32_16x5_t_u_align1(manifest);
  initialize_cutlass_tensorop_d884syrk_32x16_16x5_t_u_align1(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

