
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_simt_igemm_s8_128x128_32x2_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_128x64_32x2_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_64x128_32x2_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_64x64_32x2_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_128x32_32x2_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_32x128_32x2_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_128x128_32x2_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_128x64_32x2_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_64x128_32x2_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_64x64_32x2_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_128x32_32x2_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_32x128_32x2_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_128x128_32x2_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_128x64_32x2_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_64x128_32x2_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_64x64_32x2_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_128x32_32x2_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_32x128_32x2_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_128x128_32x2_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_128x64_32x2_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_64x128_32x2_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_64x64_32x2_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_128x32_32x2_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_igemm_s8_32x128_32x2_tt_align1(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm61_igemm_s8_gemm_operations(Manifest &manifest) {
  initialize_cutlass_simt_igemm_s8_128x128_32x2_nn_align1(manifest);
  initialize_cutlass_simt_igemm_s8_128x64_32x2_nn_align1(manifest);
  initialize_cutlass_simt_igemm_s8_64x128_32x2_nn_align1(manifest);
  initialize_cutlass_simt_igemm_s8_64x64_32x2_nn_align1(manifest);
  initialize_cutlass_simt_igemm_s8_128x32_32x2_nn_align1(manifest);
  initialize_cutlass_simt_igemm_s8_32x128_32x2_nn_align1(manifest);
  initialize_cutlass_simt_igemm_s8_128x128_32x2_nt_align1(manifest);
  initialize_cutlass_simt_igemm_s8_128x64_32x2_nt_align1(manifest);
  initialize_cutlass_simt_igemm_s8_64x128_32x2_nt_align1(manifest);
  initialize_cutlass_simt_igemm_s8_64x64_32x2_nt_align1(manifest);
  initialize_cutlass_simt_igemm_s8_128x32_32x2_nt_align1(manifest);
  initialize_cutlass_simt_igemm_s8_32x128_32x2_nt_align1(manifest);
  initialize_cutlass_simt_igemm_s8_128x128_32x2_tn_align1(manifest);
  initialize_cutlass_simt_igemm_s8_128x64_32x2_tn_align1(manifest);
  initialize_cutlass_simt_igemm_s8_64x128_32x2_tn_align1(manifest);
  initialize_cutlass_simt_igemm_s8_64x64_32x2_tn_align1(manifest);
  initialize_cutlass_simt_igemm_s8_128x32_32x2_tn_align1(manifest);
  initialize_cutlass_simt_igemm_s8_32x128_32x2_tn_align1(manifest);
  initialize_cutlass_simt_igemm_s8_128x128_32x2_tt_align1(manifest);
  initialize_cutlass_simt_igemm_s8_128x64_32x2_tt_align1(manifest);
  initialize_cutlass_simt_igemm_s8_64x128_32x2_tt_align1(manifest);
  initialize_cutlass_simt_igemm_s8_64x64_32x2_tt_align1(manifest);
  initialize_cutlass_simt_igemm_s8_128x32_32x2_tt_align1(manifest);
  initialize_cutlass_simt_igemm_s8_32x128_32x2_tt_align1(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

