
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_simt_cf32_cwgrad_optimized_cf32_128x128_8x4_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_cf32_cwgrad_optimized_cf32_64x64_8x3_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_cf32_cwgrad_optimized_cf32_64x128_16x6_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_cf32_cwgrad_optimized_cf32_128x64_16x6_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_cf32_cwgrad_optimized_cf32_64x32_16x4_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_cf32_cwgrad_optimized_cf32_32x64_16x4_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_cf32_cwgrad_optimized_cf32_32x32_16x5_nhwc_align1(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm80_cf32_cwgrad_optimized_cf32_conv2d_operations(Manifest &manifest) {
  initialize_cutlass_simt_cf32_cwgrad_optimized_cf32_128x128_8x4_nhwc_align1(manifest);
  initialize_cutlass_simt_cf32_cwgrad_optimized_cf32_64x64_8x3_nhwc_align1(manifest);
  initialize_cutlass_simt_cf32_cwgrad_optimized_cf32_64x128_16x6_nhwc_align1(manifest);
  initialize_cutlass_simt_cf32_cwgrad_optimized_cf32_128x64_16x6_nhwc_align1(manifest);
  initialize_cutlass_simt_cf32_cwgrad_optimized_cf32_64x32_16x4_nhwc_align1(manifest);
  initialize_cutlass_simt_cf32_cwgrad_optimized_cf32_32x64_16x4_nhwc_align1(manifest);
  initialize_cutlass_simt_cf32_cwgrad_optimized_cf32_32x32_16x5_nhwc_align1(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

