
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_u8_i8816gemm_u8_256x128_64x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_128x256_64x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_128x128_64x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_64x256_64x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_256x64_64x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_64x128_64x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_128x64_64x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_64x64_64x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_256x32_64x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_32x256_64x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_128x32_64x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_64x32_64x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_256x128_32x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_128x256_32x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_128x128_32x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_64x256_32x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_256x64_32x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_64x128_32x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_128x64_32x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_64x64_32x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_128x32_32x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_64x32_32x2_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_256x128_64x2_n32t32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_128x256_64x2_n32t32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_128x128_64x2_n32t32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_256x64_64x2_n32t32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_64x256_64x2_n32t32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_64x128_64x2_n32t32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_128x64_64x2_n32t32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_u8_i8816gemm_u8_64x64_64x2_n32t32_align16(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm75_u8_i8816gemm_u8_gemm_operations(Manifest &manifest) {
  initialize_cutlass_tensorop_u8_i8816gemm_u8_256x128_64x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_128x256_64x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_128x128_64x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_64x256_64x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_256x64_64x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_64x128_64x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_128x64_64x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_64x64_64x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_256x32_64x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_32x256_64x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_128x32_64x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_64x32_64x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_256x128_32x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_128x256_32x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_128x128_32x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_64x256_32x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_256x64_32x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_64x128_32x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_128x64_32x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_64x64_32x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_128x32_32x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_64x32_32x2_tn_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_256x128_64x2_n32t32_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_128x256_64x2_n32t32_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_128x128_64x2_n32t32_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_256x64_64x2_n32t32_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_64x256_64x2_n32t32_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_64x128_64x2_n32t32_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_128x64_64x2_n32t32_align16(manifest);
  initialize_cutlass_tensorop_u8_i8816gemm_u8_64x64_64x2_n32t32_align16(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

