
/*
  Generated by symm_operation.py - Do not edit.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////
#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

#include "library_internal.h"
#include "symm_operation.h"

///////////////////////////////////////////////////////////////////////////////////////////////////


// Symm operator cutlass_tensorop_s1688symm_128x256_16x3_n_rs_u_align2
using Operation_cutlass_tensorop_s1688symm_128x256_16x3_n_rs_u_align2 =
  typename cutlass::gemm::device::Symm<
    float, cutlass::layout::ColumnMajor, cutlass::SideMode::kRight, cutlass::FillMode::kUpper,
    float, cutlass::layout::ColumnMajor,
    float, cutlass::layout::ColumnMajor,
    float,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<128, 256, 16>,
    cutlass::gemm::GemmShape<64, 64, 16>,
    cutlass::gemm::GemmShape<16, 8, 8>,
    cutlass::epilogue::thread::LinearCombination<
      float,
      2,
      float,
      float
    >,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
    3,
    1,
    2,
    false,
    cutlass::arch::OpMultiplyAddFastF32
>;


///////////////////////////////////////////////////////////////////////////////////////////////////

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_s1688symm_128x256_16x3_n_rs_u_align2(Manifest &manifest) {



  manifest.append(new SymmOperation<
    Operation_cutlass_tensorop_s1688symm_128x256_16x3_n_rs_u_align2
  >("cutlass_tensorop_s1688symm_128x256_16x3_n_rs_u_align2"));



}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

///////////////////////////////////////////////////////////////////////////////////////////////////

