
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_256x128_64x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x256_64x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x128_64x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x256_64x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_256x64_64x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x128_64x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x64_64x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x64_64x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_256x32_64x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_32x256_64x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x32_64x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x32_64x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_256x128_32x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x256_32x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x128_32x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x256_32x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_256x64_32x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x128_32x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x64_32x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x64_32x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x32_32x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x32_32x2_nhwc_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_256x128_64x2_nc32hw32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x256_64x2_nc32hw32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x128_64x2_nc32hw32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_256x64_64x2_nc32hw32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x256_64x2_nc32hw32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x128_64x2_nc32hw32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x64_64x2_nc32hw32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x64_64x2_nc32hw32_align16(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm75_s8_i8816fprop_analytic_s8_conv2d_operations(Manifest &manifest) {
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_256x128_64x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x256_64x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x128_64x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x256_64x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_256x64_64x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x128_64x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x64_64x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x64_64x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_256x32_64x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_32x256_64x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x32_64x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x32_64x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_256x128_32x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x256_32x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x128_32x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x256_32x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_256x64_32x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x128_32x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x64_32x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x64_32x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x32_32x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x32_32x2_nhwc_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_256x128_64x2_nc32hw32_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x256_64x2_nc32hw32_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x128_64x2_nc32hw32_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_256x64_64x2_nc32hw32_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x256_64x2_nc32hw32_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x128_64x2_nc32hw32_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_128x64_64x2_nc32hw32_align16(manifest);
  initialize_cutlass_tensorop_s8_i8816fprop_analytic_s8_64x64_64x2_nc32hw32_align16(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

