
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_i168256andgemm_b1_256x128_512x3_tn_align128(Manifest &manifest);
void initialize_cutlass_tensorop_i168256andgemm_b1_128x256_512x3_tn_align128(Manifest &manifest);
void initialize_cutlass_tensorop_i168256andgemm_b1_256x64_512x4_tn_align128(Manifest &manifest);
void initialize_cutlass_tensorop_i168256andgemm_b1_64x256_512x4_tn_align128(Manifest &manifest);
void initialize_cutlass_tensorop_i168256andgemm_b1_128x128_512x5_tn_align128(Manifest &manifest);
void initialize_cutlass_tensorop_i168256andgemm_b1_128x64_512x6_tn_align128(Manifest &manifest);
void initialize_cutlass_tensorop_i168256andgemm_b1_64x128_512x6_tn_align128(Manifest &manifest);
void initialize_cutlass_tensorop_i168256andgemm_b1_64x64_512x10_tn_align128(Manifest &manifest);
void initialize_cutlass_tensorop_i168256andgemm_b1_256x128_1024x3_tn_align128(Manifest &manifest);
void initialize_cutlass_tensorop_i168256andgemm_b1_128x256_1024x3_tn_align128(Manifest &manifest);
void initialize_cutlass_tensorop_i168256andgemm_b1_256x64_1024x4_tn_align128(Manifest &manifest);
void initialize_cutlass_tensorop_i168256andgemm_b1_64x256_1024x4_tn_align128(Manifest &manifest);
void initialize_cutlass_tensorop_i168256andgemm_b1_128x128_1024x4_tn_align128(Manifest &manifest);
void initialize_cutlass_tensorop_i168256andgemm_b1_128x64_1024x3_tn_align128(Manifest &manifest);
void initialize_cutlass_tensorop_i168256andgemm_b1_64x128_1024x3_tn_align128(Manifest &manifest);
void initialize_cutlass_tensorop_i168256andgemm_b1_64x64_1024x5_tn_align128(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm80_i168256andgemm_b1_gemm_operations(Manifest &manifest) {
  initialize_cutlass_tensorop_i168256andgemm_b1_256x128_512x3_tn_align128(manifest);
  initialize_cutlass_tensorop_i168256andgemm_b1_128x256_512x3_tn_align128(manifest);
  initialize_cutlass_tensorop_i168256andgemm_b1_256x64_512x4_tn_align128(manifest);
  initialize_cutlass_tensorop_i168256andgemm_b1_64x256_512x4_tn_align128(manifest);
  initialize_cutlass_tensorop_i168256andgemm_b1_128x128_512x5_tn_align128(manifest);
  initialize_cutlass_tensorop_i168256andgemm_b1_128x64_512x6_tn_align128(manifest);
  initialize_cutlass_tensorop_i168256andgemm_b1_64x128_512x6_tn_align128(manifest);
  initialize_cutlass_tensorop_i168256andgemm_b1_64x64_512x10_tn_align128(manifest);
  initialize_cutlass_tensorop_i168256andgemm_b1_256x128_1024x3_tn_align128(manifest);
  initialize_cutlass_tensorop_i168256andgemm_b1_128x256_1024x3_tn_align128(manifest);
  initialize_cutlass_tensorop_i168256andgemm_b1_256x64_1024x4_tn_align128(manifest);
  initialize_cutlass_tensorop_i168256andgemm_b1_64x256_1024x4_tn_align128(manifest);
  initialize_cutlass_tensorop_i168256andgemm_b1_128x128_1024x4_tn_align128(manifest);
  initialize_cutlass_tensorop_i168256andgemm_b1_128x64_1024x3_tn_align128(manifest);
  initialize_cutlass_tensorop_i168256andgemm_b1_64x128_1024x3_tn_align128(manifest);
  initialize_cutlass_tensorop_i168256andgemm_b1_64x64_1024x5_tn_align128(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

