
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_u4_i16864gemm_u4_256x128_128x3_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_128x256_128x3_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_256x64_128x4_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_64x256_128x4_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_128x128_128x5_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_128x64_128x6_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_64x128_128x6_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_64x64_128x10_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_256x128_256x3_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_128x256_256x3_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_256x64_256x4_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_64x256_256x4_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_128x128_256x4_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_128x128_256x3_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_128x64_256x3_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_64x128_256x3_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_64x64_256x5_tn_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_256x128_128x3_n64t64_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_128x256_128x3_n64t64_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_256x64_128x4_n64t64_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_64x256_128x4_n64t64_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_128x128_128x5_n64t64_align32(Manifest &manifest);
void initialize_cutlass_tensorop_u4_i16864gemm_u4_64x128_128x6_n64t64_align32(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm80_u4_i16864gemm_u4_gemm_operations(Manifest &manifest) {
  initialize_cutlass_tensorop_u4_i16864gemm_u4_256x128_128x3_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_128x256_128x3_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_256x64_128x4_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_64x256_128x4_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_128x128_128x5_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_128x64_128x6_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_64x128_128x6_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_64x64_128x10_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_256x128_256x3_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_128x256_256x3_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_256x64_256x4_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_64x256_256x4_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_128x128_256x4_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_128x128_256x3_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_128x64_256x3_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_64x128_256x3_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_64x64_256x5_tn_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_256x128_128x3_n64t64_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_128x256_128x3_n64t64_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_256x64_128x4_n64t64_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_64x256_128x4_n64t64_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_128x128_128x5_n64t64_align32(manifest);
  initialize_cutlass_tensorop_u4_i16864gemm_u4_64x128_128x6_n64t64_align32(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

