
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_simt_hgemm_256x128_8x2_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x256_8x2_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x128_8x2_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x64_8x2_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_64x128_8x2_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_64x64_8x2_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x32_8x2_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_32x128_8x2_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_256x128_8x2_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x256_8x2_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x128_8x2_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x64_8x2_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_64x128_8x2_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_64x64_8x2_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x32_8x2_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_32x128_8x2_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_256x128_8x2_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x256_8x2_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x128_8x2_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x64_8x2_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_64x128_8x2_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_64x64_8x2_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x32_8x2_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_32x128_8x2_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_256x128_8x2_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x256_8x2_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x128_8x2_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x64_8x2_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_64x128_8x2_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_64x64_8x2_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_128x32_8x2_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_hgemm_32x128_8x2_tt_align1(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm60_hgemm_gemm_operations(Manifest &manifest) {
  initialize_cutlass_simt_hgemm_256x128_8x2_nn_align1(manifest);
  initialize_cutlass_simt_hgemm_128x256_8x2_nn_align1(manifest);
  initialize_cutlass_simt_hgemm_128x128_8x2_nn_align1(manifest);
  initialize_cutlass_simt_hgemm_128x64_8x2_nn_align1(manifest);
  initialize_cutlass_simt_hgemm_64x128_8x2_nn_align1(manifest);
  initialize_cutlass_simt_hgemm_64x64_8x2_nn_align1(manifest);
  initialize_cutlass_simt_hgemm_128x32_8x2_nn_align1(manifest);
  initialize_cutlass_simt_hgemm_32x128_8x2_nn_align1(manifest);
  initialize_cutlass_simt_hgemm_256x128_8x2_nt_align1(manifest);
  initialize_cutlass_simt_hgemm_128x256_8x2_nt_align1(manifest);
  initialize_cutlass_simt_hgemm_128x128_8x2_nt_align1(manifest);
  initialize_cutlass_simt_hgemm_128x64_8x2_nt_align1(manifest);
  initialize_cutlass_simt_hgemm_64x128_8x2_nt_align1(manifest);
  initialize_cutlass_simt_hgemm_64x64_8x2_nt_align1(manifest);
  initialize_cutlass_simt_hgemm_128x32_8x2_nt_align1(manifest);
  initialize_cutlass_simt_hgemm_32x128_8x2_nt_align1(manifest);
  initialize_cutlass_simt_hgemm_256x128_8x2_tn_align1(manifest);
  initialize_cutlass_simt_hgemm_128x256_8x2_tn_align1(manifest);
  initialize_cutlass_simt_hgemm_128x128_8x2_tn_align1(manifest);
  initialize_cutlass_simt_hgemm_128x64_8x2_tn_align1(manifest);
  initialize_cutlass_simt_hgemm_64x128_8x2_tn_align1(manifest);
  initialize_cutlass_simt_hgemm_64x64_8x2_tn_align1(manifest);
  initialize_cutlass_simt_hgemm_128x32_8x2_tn_align1(manifest);
  initialize_cutlass_simt_hgemm_32x128_8x2_tn_align1(manifest);
  initialize_cutlass_simt_hgemm_256x128_8x2_tt_align1(manifest);
  initialize_cutlass_simt_hgemm_128x256_8x2_tt_align1(manifest);
  initialize_cutlass_simt_hgemm_128x128_8x2_tt_align1(manifest);
  initialize_cutlass_simt_hgemm_128x64_8x2_tt_align1(manifest);
  initialize_cutlass_simt_hgemm_64x128_8x2_tt_align1(manifest);
  initialize_cutlass_simt_hgemm_64x64_8x2_tt_align1(manifest);
  initialize_cutlass_simt_hgemm_128x32_8x2_tt_align1(manifest);
  initialize_cutlass_simt_hgemm_32x128_8x2_tt_align1(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

