
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_simt_hfprop_optimized_64x32x9_1x8x8x32_3_filter3x3_nhwc_depthwise_align8(Manifest &manifest);
void initialize_cutlass_simt_hfprop_optimized_64x64x9_1x8x8x64_3_filter3x3_nhwc_depthwise_align8(Manifest &manifest);
void initialize_cutlass_simt_hfprop_optimized_64x16x9_1x8x8x16_3_filter3x3_nhwc_depthwise_align8(Manifest &manifest);
void initialize_cutlass_simt_hfprop_optimized_100x64x9_1x10x10x64_2_filter3x3_nhwc_depthwise_align8(Manifest &manifest);
void initialize_cutlass_simt_hfprop_optimized_16x32x9_1x4x4x32_4_filter3x3_nhwc_depthwise_align8(Manifest &manifest);
void initialize_cutlass_simt_hfprop_optimized_16x64x9_1x4x4x64_4_filter3x3_nhwc_depthwise_align8(Manifest &manifest);
void initialize_cutlass_simt_hfprop_optimized_16x16x9_1x4x4x16_4_filter3x3_nhwc_depthwise_align8(Manifest &manifest);
void initialize_cutlass_simt_hfprop_optimized_64x32x25_1x8x8x32_3_filter5x5_nhwc_depthwise_align8(Manifest &manifest);
void initialize_cutlass_simt_hfprop_optimized_64x64x25_1x8x8x64_3_filter5x5_nhwc_depthwise_align8(Manifest &manifest);
void initialize_cutlass_simt_hfprop_optimized_64x16x25_1x8x8x16_3_filter5x5_nhwc_depthwise_align8(Manifest &manifest);
void initialize_cutlass_simt_hfprop_optimized_100x64x25_1x10x10x64_2_filter5x5_nhwc_depthwise_align8(Manifest &manifest);
void initialize_cutlass_simt_hfprop_optimized_16x32x25_1x4x4x32_4_filter5x5_nhwc_depthwise_align8(Manifest &manifest);
void initialize_cutlass_simt_hfprop_optimized_16x64x25_1x4x4x64_4_filter5x5_nhwc_depthwise_align8(Manifest &manifest);
void initialize_cutlass_simt_hfprop_optimized_16x16x25_1x4x4x16_4_filter5x5_nhwc_depthwise_align8(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm60_hfprop_optimized_conv2d_operations(Manifest &manifest) {
  initialize_cutlass_simt_hfprop_optimized_64x32x9_1x8x8x32_3_filter3x3_nhwc_depthwise_align8(manifest);
  initialize_cutlass_simt_hfprop_optimized_64x64x9_1x8x8x64_3_filter3x3_nhwc_depthwise_align8(manifest);
  initialize_cutlass_simt_hfprop_optimized_64x16x9_1x8x8x16_3_filter3x3_nhwc_depthwise_align8(manifest);
  initialize_cutlass_simt_hfprop_optimized_100x64x9_1x10x10x64_2_filter3x3_nhwc_depthwise_align8(manifest);
  initialize_cutlass_simt_hfprop_optimized_16x32x9_1x4x4x32_4_filter3x3_nhwc_depthwise_align8(manifest);
  initialize_cutlass_simt_hfprop_optimized_16x64x9_1x4x4x64_4_filter3x3_nhwc_depthwise_align8(manifest);
  initialize_cutlass_simt_hfprop_optimized_16x16x9_1x4x4x16_4_filter3x3_nhwc_depthwise_align8(manifest);
  initialize_cutlass_simt_hfprop_optimized_64x32x25_1x8x8x32_3_filter5x5_nhwc_depthwise_align8(manifest);
  initialize_cutlass_simt_hfprop_optimized_64x64x25_1x8x8x64_3_filter5x5_nhwc_depthwise_align8(manifest);
  initialize_cutlass_simt_hfprop_optimized_64x16x25_1x8x8x16_3_filter5x5_nhwc_depthwise_align8(manifest);
  initialize_cutlass_simt_hfprop_optimized_100x64x25_1x10x10x64_2_filter5x5_nhwc_depthwise_align8(manifest);
  initialize_cutlass_simt_hfprop_optimized_16x32x25_1x4x4x32_4_filter5x5_nhwc_depthwise_align8(manifest);
  initialize_cutlass_simt_hfprop_optimized_16x64x25_1x4x4x64_4_filter5x5_nhwc_depthwise_align8(manifest);
  initialize_cutlass_simt_hfprop_optimized_16x16x25_1x4x4x16_4_filter5x5_nhwc_depthwise_align8(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

