
/*
  Generated by conv2d_operation.py - Do not edit.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

#include "library_internal.h"
#include "conv2d_operation.h"

///////////////////////////////////////////////////////////////////////////////////////////////////


  // Conv2dFprop Optimized kernel instance "cutlass_simt_hfprop_optimized_16x64x25_1x4x4x64_4_filter5x5_nhwc_depthwise_align8"
  using cutlass_simt_hfprop_optimized_16x64x25_1x4x4x64_4_filter5x5_nhwc_depthwise_align8_base =
  typename cutlass::conv::kernel::DefaultDepthwiseDirect2dConvFprop<
    cutlass::half_t,
    cutlass::layout::TensorNHWC,
    cutlass::half_t,
    cutlass::layout::TensorNHWC,
    cutlass::half_t,
    cutlass::layout::TensorNHWC,
    cutlass::half_t,
    cutlass::arch::OpClassSimt,
    cutlass::arch::Sm60,
    cutlass::gemm::GemmShape<16, 64, 25>,
    cutlass::conv::TensorNHWCShape<1, 4, 4, 64>,
    cutlass::MatrixShape<5, 5>,
    cutlass::gemm::GemmShape<4, 64, 25>,
    cutlass::gemm::GemmShape<1, 1, 1>,
    cutlass::epilogue::thread::LinearCombination<
      cutlass::half_t,
      8,
      cutlass::half_t,
      cutlass::half_t,
      cutlass::epilogue::thread::ScaleType::OnlyAlphaScaling
    >,

    cutlass::conv::threadblock::DepthwiseDirect2dConvIdentityThreadblockSwizzle<
          1,
          1,
          4,
          4>,
    4,
    cutlass::arch::OpMultiplyAdd,
    cutlass::conv::IteratorAlgorithm::kOptimized,
    cutlass::conv::StrideSupport::kStrided,
    cutlass::MatrixShape<-1, -1>,
    cutlass::MatrixShape<-1, -1>
  >::Kernel;

// Derived class
struct cutlass_simt_hfprop_optimized_16x64x25_1x4x4x64_4_filter5x5_nhwc_depthwise_align8 :
  public cutlass_simt_hfprop_optimized_16x64x25_1x4x4x64_4_filter5x5_nhwc_depthwise_align8_base { };

///////////////////////////////////////////////////////////////////////////////////////////////////



namespace cutlass {
namespace library {

// Initialize all instances
void initialize_cutlass_simt_hfprop_optimized_16x64x25_1x4x4x64_4_filter5x5_nhwc_depthwise_align8(Manifest &manifest) {

  using Operation_cutlass_simt_hfprop_optimized_16x64x25_1x4x4x64_4_filter5x5_nhwc_depthwise_align8 = cutlass::conv::device::DirectConvolution<
    cutlass_simt_hfprop_optimized_16x64x25_1x4x4x64_4_filter5x5_nhwc_depthwise_align8>;

  manifest.append(new cutlass::library::DirectConv2dOperation<
      Operation_cutlass_simt_hfprop_optimized_16x64x25_1x4x4x64_4_filter5x5_nhwc_depthwise_align8
    >(
      "cutlass_simt_hfprop_optimized_16x64x25_1x4x4x64_4_filter5x5_nhwc_depthwise_align8"
    ));

}


///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

///////////////////////////////////////////////////////////////////////////////////////////////////

