
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_256x128_32x3(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x256_32x3(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_256x64_32x3(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_256x64_32x4(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_64x256_32x4(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x128_32x3(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x128_32x4(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x128_32x5(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x64_32x6(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_64x128_32x6(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_64x64_32x10(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_256x128_64x3(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x256_64x3(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_256x64_64x4(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_64x256_64x4(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x128_64x4(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_256x64_64x3(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_64x256_64x3(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x128_64x3(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x64_64x3(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_64x128_64x3(Manifest &manifest);
void initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_64x64_64x5(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm80_f16_s16816wgrad3d_optimized_f16_conv3d_operations(Manifest &manifest) {
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_256x128_32x3(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x256_32x3(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_256x64_32x3(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_256x64_32x4(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_64x256_32x4(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x128_32x3(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x128_32x4(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x128_32x5(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x64_32x6(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_64x128_32x6(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_64x64_32x10(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_256x128_64x3(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x256_64x3(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_256x64_64x4(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_64x256_64x4(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x128_64x4(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_256x64_64x3(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_64x256_64x3(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x128_64x3(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_128x64_64x3(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_64x128_64x3(manifest);
  initialize_cutlass_tensorop_f16_s16816wgrad3d_optimized_f16_64x64_64x5(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

