
/*
  Generated by conv2d_operation.py - Do not edit.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

#include "library_internal.h"
#include "conv2d_operation.h"

///////////////////////////////////////////////////////////////////////////////////////////////////


  // Conv2dFprop Optimized kernel instance "cutlass_tensorop_s4_i16864fprop_optimized_s4_64x64_128x10_nhwc_single_group_align32"
  using cutlass_tensorop_s4_i16864fprop_optimized_s4_64x64_128x10_nhwc_single_group_align32_base =
  typename cutlass::conv::kernel::DefaultConv2dGroupFprop<
    cutlass::int4b_t,
    cutlass::layout::TensorNHWC,
    cutlass::int4b_t,
    cutlass::layout::TensorNHWC,
    cutlass::int4b_t,
    cutlass::layout::TensorNHWC,
    int32_t,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<64, 64, 128>,
    cutlass::gemm::GemmShape<32, 32, 128 >,
    cutlass::gemm::GemmShape<16, 8, 64>,
    cutlass::epilogue::thread::LinearCombinationClamp<
      cutlass::int4b_t,
      8,
      int32_t,
      float
    >,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<4>, // cutlass::gemm::threadblock::GemmSplitKIdentityThreadblockSwizzle<>,
    10,
    cutlass::arch::OpMultiplyAddSaturate,
    cutlass::conv::GroupMode::kSingleGroup,
    cutlass::conv::IteratorAlgorithm::kOptimized,
    cutlass::conv::StrideSupport::kUnity,
    32,
    32
  >::Kernel;

// Derived class
struct cutlass_tensorop_s4_i16864fprop_optimized_s4_64x64_128x10_nhwc_single_group_align32 :
  public cutlass_tensorop_s4_i16864fprop_optimized_s4_64x64_128x10_nhwc_single_group_align32_base { };

///////////////////////////////////////////////////////////////////////////////////////////////////



namespace cutlass {
namespace library {

// Initialize all instances
void initialize_cutlass_tensorop_s4_i16864fprop_optimized_s4_64x64_128x10_nhwc_single_group_align32(Manifest &manifest) {

  using Operation_cutlass_tensorop_s4_i16864fprop_optimized_s4_64x64_128x10_nhwc_single_group_align32 = cutlass::conv::device::ImplicitGemmConvolution<
    cutlass_tensorop_s4_i16864fprop_optimized_s4_64x64_128x10_nhwc_single_group_align32>;

  manifest.append(new cutlass::library::Conv2dOperation<
      Operation_cutlass_tensorop_s4_i16864fprop_optimized_s4_64x64_128x10_nhwc_single_group_align32
    >(
      "cutlass_tensorop_s4_i16864fprop_optimized_s4_64x64_128x10_nhwc_single_group_align32"
    ));

}


///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

///////////////////////////////////////////////////////////////////////////////////////////////////

