
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_simt_dgemm_128x128_8x3_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_128x64_8x4_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_64x128_8x4_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_64x64_8x5_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_128x32_8x5_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_32x128_8x5_nn_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_128x128_8x3_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_128x64_8x4_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_64x128_8x4_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_64x64_8x5_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_128x32_8x5_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_32x128_8x5_nt_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_128x128_8x3_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_128x64_8x4_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_64x128_8x4_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_64x64_8x5_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_128x32_8x5_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_32x128_8x5_tn_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_128x128_8x3_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_128x64_8x4_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_64x128_8x4_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_64x64_8x5_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_128x32_8x5_tt_align1(Manifest &manifest);
void initialize_cutlass_simt_dgemm_32x128_8x5_tt_align1(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm80_dgemm_gemm_operations(Manifest &manifest) {
  initialize_cutlass_simt_dgemm_128x128_8x3_nn_align1(manifest);
  initialize_cutlass_simt_dgemm_128x64_8x4_nn_align1(manifest);
  initialize_cutlass_simt_dgemm_64x128_8x4_nn_align1(manifest);
  initialize_cutlass_simt_dgemm_64x64_8x5_nn_align1(manifest);
  initialize_cutlass_simt_dgemm_128x32_8x5_nn_align1(manifest);
  initialize_cutlass_simt_dgemm_32x128_8x5_nn_align1(manifest);
  initialize_cutlass_simt_dgemm_128x128_8x3_nt_align1(manifest);
  initialize_cutlass_simt_dgemm_128x64_8x4_nt_align1(manifest);
  initialize_cutlass_simt_dgemm_64x128_8x4_nt_align1(manifest);
  initialize_cutlass_simt_dgemm_64x64_8x5_nt_align1(manifest);
  initialize_cutlass_simt_dgemm_128x32_8x5_nt_align1(manifest);
  initialize_cutlass_simt_dgemm_32x128_8x5_nt_align1(manifest);
  initialize_cutlass_simt_dgemm_128x128_8x3_tn_align1(manifest);
  initialize_cutlass_simt_dgemm_128x64_8x4_tn_align1(manifest);
  initialize_cutlass_simt_dgemm_64x128_8x4_tn_align1(manifest);
  initialize_cutlass_simt_dgemm_64x64_8x5_tn_align1(manifest);
  initialize_cutlass_simt_dgemm_128x32_8x5_tn_align1(manifest);
  initialize_cutlass_simt_dgemm_32x128_8x5_tn_align1(manifest);
  initialize_cutlass_simt_dgemm_128x128_8x3_tt_align1(manifest);
  initialize_cutlass_simt_dgemm_128x64_8x4_tt_align1(manifest);
  initialize_cutlass_simt_dgemm_64x128_8x4_tt_align1(manifest);
  initialize_cutlass_simt_dgemm_64x64_8x5_tt_align1(manifest);
  initialize_cutlass_simt_dgemm_128x32_8x5_tt_align1(manifest);
  initialize_cutlass_simt_dgemm_32x128_8x5_tt_align1(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

