
/*
  Generated by trmm_operation.py - Do not edit.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////
#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

#include "library_internal.h"
#include "trmm_operation.h"

///////////////////////////////////////////////////////////////////////////////////////////////////


// Trmm operator cutlass_tensorop_s1688trmm_64x64_16x10_nn_ls_l_nu_align4
using Operation_cutlass_tensorop_s1688trmm_64x64_16x10_nn_ls_l_nu_align4 =
  typename cutlass::gemm::device::Trmm<
    float, cutlass::layout::ColumnMajor,
    cutlass::SideMode::kLeft, cutlass::FillMode::kLower, cutlass::DiagType::kNonUnit,
    float, cutlass::layout::ColumnMajor,
    float, cutlass::layout::ColumnMajor,
    float,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<64, 64, 16>,
    cutlass::gemm::GemmShape<32, 32, 16>,
    cutlass::gemm::GemmShape<16, 8, 8>,
    cutlass::epilogue::thread::LinearCombination<
      float,
      4,
      float,
      float,
      cutlass::epilogue::thread::ScaleType::OnlyAlphaScaling
    >,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
    10,
    1,
    4,
    false,
    cutlass::arch::OpMultiplyAddFastF32
>;


///////////////////////////////////////////////////////////////////////////////////////////////////

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_s1688trmm_64x64_16x10_nn_ls_l_nu_align4(Manifest &manifest) {



  manifest.append(new TrmmOperation<
    Operation_cutlass_tensorop_s1688trmm_64x64_16x10_nn_ls_l_nu_align4
  >("cutlass_tensorop_s1688trmm_64x64_16x10_nn_ls_l_nu_align4"));



}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

///////////////////////////////////////////////////////////////////////////////////////////////////

