
/*
  Generated by conv3d_operation.py - Do not edit.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

#include "library_internal.h"
#include "conv3d_operation.h"

///////////////////////////////////////////////////////////////////////////////////////////////////


  // Conv3dWgrad Optimized kernel instance "cutlass_tensorop_s16816wgrad3d_optimized_f16_64x64_64x5"
  using cutlass_tensorop_s16816wgrad3d_optimized_f16_64x64_64x5_base =
  typename cutlass::conv::kernel::DefaultConv3dWgrad<
    cutlass::half_t,
    cutlass::layout::TensorNDHWC,
    cutlass::half_t,
    cutlass::layout::TensorNDHWC,
    float,
    cutlass::layout::TensorNDHWC,
    float,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<64, 64, 64>,
    cutlass::gemm::GemmShape<32, 32, 64 >,
    cutlass::gemm::GemmShape<16, 8, 16>,
    cutlass::epilogue::thread::LinearCombination<
      float,
      4,
      float,
      float
    >,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<4>, // cutlass::gemm::threadblock::GemmSplitKIdentityThreadblockSwizzle<>,
    5,
    cutlass::arch::OpMultiplyAdd,
    cutlass::conv::IteratorAlgorithm::kOptimized,
    cutlass::conv::StrideSupport::kStrided
  >::Kernel;

// Derived class
struct cutlass_tensorop_s16816wgrad3d_optimized_f16_64x64_64x5 :
  public cutlass_tensorop_s16816wgrad3d_optimized_f16_64x64_64x5_base { };

///////////////////////////////////////////////////////////////////////////////////////////////////



namespace cutlass {
namespace library {

// Initialize all instances
void initialize_cutlass_tensorop_s16816wgrad3d_optimized_f16_64x64_64x5(Manifest &manifest) {

  using Operation_cutlass_tensorop_s16816wgrad3d_optimized_f16_64x64_64x5 = cutlass::conv::device::ImplicitGemmConvolution<
    cutlass_tensorop_s16816wgrad3d_optimized_f16_64x64_64x5>;

  manifest.append(new cutlass::library::Conv3dOperation<
      Operation_cutlass_tensorop_s16816wgrad3d_optimized_f16_64x64_64x5
    >(
      "cutlass_tensorop_s16816wgrad3d_optimized_f16_64x64_64x5"
    ));

}


///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

///////////////////////////////////////////////////////////////////////////////////////////////////

