
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_h16816dgrad3d_optimized_256x128_32x3_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x256_32x3_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_256x64_32x3_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_256x64_32x4_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_64x256_32x4_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x128_32x3_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x128_32x4_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x128_32x5_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x64_32x6_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_64x128_32x6_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_64x64_32x10_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_256x128_64x3_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x256_64x3_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_256x64_64x4_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_64x256_64x4_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x128_64x4_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_256x64_64x3_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_64x256_64x3_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x128_64x3_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x64_64x3_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_64x128_64x3_unity_stride(Manifest &manifest);
void initialize_cutlass_tensorop_h16816dgrad3d_optimized_64x64_64x5_unity_stride(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm80_h16816dgrad3d_optimized_conv3d_operations(Manifest &manifest) {
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_256x128_32x3_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x256_32x3_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_256x64_32x3_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_256x64_32x4_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_64x256_32x4_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x128_32x3_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x128_32x4_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x128_32x5_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x64_32x6_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_64x128_32x6_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_64x64_32x10_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_256x128_64x3_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x256_64x3_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_256x64_64x4_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_64x256_64x4_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x128_64x4_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_256x64_64x3_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_64x256_64x3_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x128_64x3_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_128x64_64x3_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_64x128_64x3_unity_stride(manifest);
  initialize_cutlass_tensorop_h16816dgrad3d_optimized_64x64_64x5_unity_stride(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

