
/*
  Generated by conv2d_operation.py - Do not edit.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

#include "library_internal.h"
#include "conv2d_operation.h"

///////////////////////////////////////////////////////////////////////////////////////////////////


  // Conv2dDgrad Analytic kernel instance "cutlass_tensorop_s1688bf16dgrad_analytic_64x128_16x6_nhwc_unity_stride_align2"
  using cutlass_tensorop_s1688bf16dgrad_analytic_64x128_16x6_nhwc_unity_stride_align2_base =
  typename cutlass::conv::kernel::DefaultConv2dDgrad<
    float,
    cutlass::layout::TensorNHWC,
    float,
    cutlass::layout::TensorNHWC,
    float,
    cutlass::layout::TensorNHWC,
    float,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<64, 128, 16>,
    cutlass::gemm::GemmShape<32, 64, 16 >,
    cutlass::gemm::GemmShape<16, 8, 8>,
    cutlass::epilogue::thread::LinearCombination<
      float,
      2,
      float,
      float
    >,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<4>, // cutlass::gemm::threadblock::GemmSplitKIdentityThreadblockSwizzle<>,
    6,
    cutlass::arch::OpMultiplyAddFastBF16,
    cutlass::conv::IteratorAlgorithm::kAnalytic,
    cutlass::conv::StrideSupport::kUnity,
    2,
    2
  >::Kernel;

// Derived class
struct cutlass_tensorop_s1688bf16dgrad_analytic_64x128_16x6_nhwc_unity_stride_align2 :
  public cutlass_tensorop_s1688bf16dgrad_analytic_64x128_16x6_nhwc_unity_stride_align2_base { };

///////////////////////////////////////////////////////////////////////////////////////////////////



namespace cutlass {
namespace library {

// Initialize all instances
void initialize_cutlass_tensorop_s1688bf16dgrad_analytic_64x128_16x6_nhwc_unity_stride_align2(Manifest &manifest) {

  using Operation_cutlass_tensorop_s1688bf16dgrad_analytic_64x128_16x6_nhwc_unity_stride_align2 = cutlass::conv::device::ImplicitGemmConvolution<
    cutlass_tensorop_s1688bf16dgrad_analytic_64x128_16x6_nhwc_unity_stride_align2>;

  manifest.append(new cutlass::library::Conv2dOperation<
      Operation_cutlass_tensorop_s1688bf16dgrad_analytic_64x128_16x6_nhwc_unity_stride_align2
    >(
      "cutlass_tensorop_s1688bf16dgrad_analytic_64x128_16x6_nhwc_unity_stride_align2"
    ));

}


///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

///////////////////////////////////////////////////////////////////////////////////////////////////

