
/*
  Generated by conv3d_operation.py - Do not edit.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

#include "library_internal.h"
#include "conv3d_operation.h"

///////////////////////////////////////////////////////////////////////////////////////////////////


  // Conv3dDgrad Analytic kernel instance "cutlass_tensorop_h16816dgrad3d_analytic_128x128_64x4"
  using cutlass_tensorop_h16816dgrad3d_analytic_128x128_64x4_base =
  typename cutlass::conv::kernel::DefaultConv3dDgrad<
    cutlass::half_t,
    cutlass::layout::TensorNDHWC,
    cutlass::half_t,
    cutlass::layout::TensorNDHWC,
    cutlass::half_t,
    cutlass::layout::TensorNDHWC,
    cutlass::half_t,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<128, 128, 64>,
    cutlass::gemm::GemmShape<64, 64, 64 >,
    cutlass::gemm::GemmShape<16, 8, 16>,
    cutlass::epilogue::thread::LinearCombination<
      cutlass::half_t,
      8,
      cutlass::half_t,
      cutlass::half_t
    >,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<4>, // cutlass::gemm::threadblock::GemmSplitKIdentityThreadblockSwizzle<>,
    4,
    cutlass::arch::OpMultiplyAdd,
    cutlass::conv::IteratorAlgorithm::kAnalytic,
    cutlass::conv::StrideSupport::kStrided
  >::Kernel;

// Derived class
struct cutlass_tensorop_h16816dgrad3d_analytic_128x128_64x4 :
  public cutlass_tensorop_h16816dgrad3d_analytic_128x128_64x4_base { };

///////////////////////////////////////////////////////////////////////////////////////////////////



namespace cutlass {
namespace library {

// Initialize all instances
void initialize_cutlass_tensorop_h16816dgrad3d_analytic_128x128_64x4(Manifest &manifest) {

  using Operation_cutlass_tensorop_h16816dgrad3d_analytic_128x128_64x4 = cutlass::conv::device::ImplicitGemmConvolution<
    cutlass_tensorop_h16816dgrad3d_analytic_128x128_64x4>;

  manifest.append(new cutlass::library::Conv3dOperation<
      Operation_cutlass_tensorop_h16816dgrad3d_analytic_128x128_64x4
    >(
      "cutlass_tensorop_h16816dgrad3d_analytic_128x128_64x4"
    ));

}


///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

///////////////////////////////////////////////////////////////////////////////////////////////////

