
/*
  Generated by conv2d_operation.py - Do not edit.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

#include "library_internal.h"
#include "conv2d_operation.h"

///////////////////////////////////////////////////////////////////////////////////////////////////


  // Conv2dFprop Few_channels kernel instance "cutlass_tensorop_s8_i16832fprop_few_channels_s8_256x64_64x4_nhwc_align4"
  using cutlass_tensorop_s8_i16832fprop_few_channels_s8_256x64_64x4_nhwc_align4_base =
  typename cutlass::conv::kernel::DefaultConv2dFprop<
    int8_t,
    cutlass::layout::TensorNHWC,
    int8_t,
    cutlass::layout::TensorNHWC,
    int8_t,
    cutlass::layout::TensorNHWC,
    int32_t,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<256, 64, 64>,
    cutlass::gemm::GemmShape<64, 64, 64 >,
    cutlass::gemm::GemmShape<16, 8, 32>,
    cutlass::epilogue::thread::LinearCombinationClamp<
      int8_t,
      8,
      int32_t,
      float
    >,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<4>, // cutlass::gemm::threadblock::GemmSplitKIdentityThreadblockSwizzle<>,
    4,
    cutlass::arch::OpMultiplyAddSaturate,
    cutlass::conv::IteratorAlgorithm::kFewChannels,
    cutlass::conv::StrideSupport::kStrided,
    4,
    4
  >::Kernel;

// Derived class
struct cutlass_tensorop_s8_i16832fprop_few_channels_s8_256x64_64x4_nhwc_align4 :
  public cutlass_tensorop_s8_i16832fprop_few_channels_s8_256x64_64x4_nhwc_align4_base { };

///////////////////////////////////////////////////////////////////////////////////////////////////



namespace cutlass {
namespace library {

// Initialize all instances
void initialize_cutlass_tensorop_s8_i16832fprop_few_channels_s8_256x64_64x4_nhwc_align4(Manifest &manifest) {

  using Operation_cutlass_tensorop_s8_i16832fprop_few_channels_s8_256x64_64x4_nhwc_align4 = cutlass::conv::device::ImplicitGemmConvolution<
    cutlass_tensorop_s8_i16832fprop_few_channels_s8_256x64_64x4_nhwc_align4>;

  manifest.append(new cutlass::library::Conv2dOperation<
      Operation_cutlass_tensorop_s8_i16832fprop_few_channels_s8_256x64_64x4_nhwc_align4
    >(
      "cutlass_tensorop_s8_i16832fprop_few_channels_s8_256x64_64x4_nhwc_align4"
    ));

}


///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

///////////////////////////////////////////////////////////////////////////////////////////////////

