
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_s8_i16832gemm_s8_256x128_64x3_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_128x256_64x3_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_256x64_64x4_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_64x256_64x4_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_256x32_64x4_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_32x256_64x4_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_128x128_64x5_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_128x64_64x6_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_64x128_64x6_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_128x32_64x6_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_32x128_64x6_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_64x64_64x10_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_256x128_128x3_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_128x256_128x3_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_256x64_128x4_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_64x256_128x4_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_256x32_128x4_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_32x256_128x4_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_128x128_128x4_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_128x64_128x3_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_64x128_128x3_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_128x32_128x4_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_32x128_128x4_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_64x64_128x5_tn_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_256x128_64x3_n32t32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_128x256_64x3_n32t32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_256x64_64x4_n32t32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_64x256_64x4_n32t32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_128x128_64x5_n32t32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_128x64_64x6_n32t32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_64x128_64x6_n32t32_align16(Manifest &manifest);
void initialize_cutlass_tensorop_s8_i16832gemm_s8_64x64_64x10_n32t32_align16(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm80_s8_i16832gemm_s8_gemm_operations(Manifest &manifest) {
  initialize_cutlass_tensorop_s8_i16832gemm_s8_256x128_64x3_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_128x256_64x3_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_256x64_64x4_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_64x256_64x4_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_256x32_64x4_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_32x256_64x4_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_128x128_64x5_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_128x64_64x6_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_64x128_64x6_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_128x32_64x6_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_32x128_64x6_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_64x64_64x10_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_256x128_128x3_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_128x256_128x3_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_256x64_128x4_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_64x256_128x4_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_256x32_128x4_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_32x256_128x4_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_128x128_128x4_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_128x64_128x3_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_64x128_128x3_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_128x32_128x4_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_32x128_128x4_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_64x64_128x5_tn_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_256x128_64x3_n32t32_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_128x256_64x3_n32t32_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_256x64_64x4_n32t32_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_64x256_64x4_n32t32_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_128x128_64x5_n32t32_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_128x64_64x6_n32t32_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_64x128_64x6_n32t32_align16(manifest);
  initialize_cutlass_tensorop_s8_i16832gemm_s8_64x64_64x10_n32t32_align16(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

