
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_simt_sdgrad_analytic_256x128_8x5_nhwc_unity_stride_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_256x128_8x5_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_128x256_8x5_nhwc_unity_stride_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_128x256_8x5_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_128x128_8x5_nhwc_unity_stride_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_128x128_8x5_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_256x128_8x4_nhwc_unity_stride_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_256x128_8x4_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_128x256_8x4_nhwc_unity_stride_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_128x256_8x4_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_128x128_8x4_nhwc_unity_stride_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_128x128_8x4_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_128x64_8x5_nhwc_unity_stride_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_128x64_8x5_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_64x128_8x5_nhwc_unity_stride_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_64x128_8x5_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_64x64_8x5_nhwc_unity_stride_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_64x64_8x5_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_128x32_8x5_nhwc_unity_stride_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_128x32_8x5_nhwc_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_32x128_8x5_nhwc_unity_stride_align1(Manifest &manifest);
void initialize_cutlass_simt_sdgrad_analytic_32x128_8x5_nhwc_align1(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm80_sdgrad_analytic_conv2d_operations(Manifest &manifest) {
  initialize_cutlass_simt_sdgrad_analytic_256x128_8x5_nhwc_unity_stride_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_256x128_8x5_nhwc_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_128x256_8x5_nhwc_unity_stride_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_128x256_8x5_nhwc_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_128x128_8x5_nhwc_unity_stride_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_128x128_8x5_nhwc_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_256x128_8x4_nhwc_unity_stride_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_256x128_8x4_nhwc_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_128x256_8x4_nhwc_unity_stride_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_128x256_8x4_nhwc_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_128x128_8x4_nhwc_unity_stride_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_128x128_8x4_nhwc_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_128x64_8x5_nhwc_unity_stride_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_128x64_8x5_nhwc_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_64x128_8x5_nhwc_unity_stride_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_64x128_8x5_nhwc_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_64x64_8x5_nhwc_unity_stride_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_64x64_8x5_nhwc_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_128x32_8x5_nhwc_unity_stride_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_128x32_8x5_nhwc_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_32x128_8x5_nhwc_unity_stride_align1(manifest);
  initialize_cutlass_simt_sdgrad_analytic_32x128_8x5_nhwc_align1(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

