
/*
  Generated by trmm_operation.py - Do not edit.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////
#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

#include "library_internal.h"
#include "trmm_operation.h"

///////////////////////////////////////////////////////////////////////////////////////////////////


// Trmm operator cutlass_tensorop_s1688tf32trmm_256x64_16x4_nn_rs_u_un_align2
using Operation_cutlass_tensorop_s1688tf32trmm_256x64_16x4_nn_rs_u_un_align2 =
  typename cutlass::gemm::device::Trmm<
    float, cutlass::layout::ColumnMajor,
    cutlass::SideMode::kRight, cutlass::FillMode::kUpper, cutlass::DiagType::kUnit,
    float, cutlass::layout::ColumnMajor,
    float, cutlass::layout::ColumnMajor,
    float,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<256, 64, 16>,
    cutlass::gemm::GemmShape<64, 64, 16>,
    cutlass::gemm::GemmShape<16, 8, 8>,
    cutlass::epilogue::thread::LinearCombination<
      float,
      2,
      float,
      float,
      cutlass::epilogue::thread::ScaleType::OnlyAlphaScaling
    >,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
    4,
    1,
    2,
    false,
    cutlass::arch::OpMultiplyAdd
>;


///////////////////////////////////////////////////////////////////////////////////////////////////

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_s1688tf32trmm_256x64_16x4_nn_rs_u_un_align2(Manifest &manifest) {



  manifest.append(new TrmmOperation<
    Operation_cutlass_tensorop_s1688tf32trmm_256x64_16x4_nn_rs_u_un_align2
  >("cutlass_tensorop_s1688tf32trmm_256x64_16x4_nn_rs_u_un_align2"));



}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

///////////////////////////////////////////////////////////////////////////////////////////////////

