
/*
  Generated by conv2d_operation.py - Do not edit.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

#include "library_internal.h"
#include "conv2d_operation.h"

///////////////////////////////////////////////////////////////////////////////////////////////////


  // Conv2dDgrad Analytic kernel instance "cutlass_tensorop_s1688dgrad_analytic_tf32_256x64_32x4_nhwc_align1"
  using cutlass_tensorop_s1688dgrad_analytic_tf32_256x64_32x4_nhwc_align1_base =
  typename cutlass::conv::kernel::DefaultConv2dDgrad<
    cutlass::tfloat32_t,
    cutlass::layout::TensorNHWC,
    cutlass::tfloat32_t,
    cutlass::layout::TensorNHWC,
    float,
    cutlass::layout::TensorNHWC,
    float,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<256, 64, 32>,
    cutlass::gemm::GemmShape<64, 64, 32 >,
    cutlass::gemm::GemmShape<16, 8, 8>,
    cutlass::epilogue::thread::LinearCombination<
      float,
      1,
      float,
      float
    >,
    cutlass::conv::threadblock::StridedDgradIdentityThreadblockSwizzle<1>, // cutlass::gemm::threadblock::GemmSplitKIdentityThreadblockSwizzle<>,
    4,
    cutlass::arch::OpMultiplyAdd,
    cutlass::conv::IteratorAlgorithm::kAnalytic,
    cutlass::conv::StrideSupport::kStrided,
    1,
    1
  >::Kernel;

// Derived class
struct cutlass_tensorop_s1688dgrad_analytic_tf32_256x64_32x4_nhwc_align1 :
  public cutlass_tensorop_s1688dgrad_analytic_tf32_256x64_32x4_nhwc_align1_base { };

///////////////////////////////////////////////////////////////////////////////////////////////////



namespace cutlass {
namespace library {

// Initialize all instances
void initialize_cutlass_tensorop_s1688dgrad_analytic_tf32_256x64_32x4_nhwc_align1(Manifest &manifest) {

  using Operation_cutlass_tensorop_s1688dgrad_analytic_tf32_256x64_32x4_nhwc_align1 = cutlass::conv::device::ImplicitGemmConvolution<
    cutlass_tensorop_s1688dgrad_analytic_tf32_256x64_32x4_nhwc_align1>;

  manifest.append(new cutlass::library::Conv2dOperation<
      Operation_cutlass_tensorop_s1688dgrad_analytic_tf32_256x64_32x4_nhwc_align1
    >(
      "cutlass_tensorop_s1688dgrad_analytic_tf32_256x64_32x4_nhwc_align1"
    ));

}


///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

///////////////////////////////////////////////////////////////////////////////////////////////////

