
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_d884gemm_128x128_16x3_nn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_256x64_16x3_nn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x256_16x3_nn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_256x32_16x3_nn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x256_16x3_nn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_128x64_16x3_nn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x128_16x3_nn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x64_16x4_nn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x32_16x4_nn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x64_16x4_nn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x32_16x5_nn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_16x32_16x5_nn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x16_16x5_nn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_128x128_16x3_nt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_256x64_16x3_nt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x256_16x3_nt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_256x32_16x3_nt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x256_16x3_nt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_128x64_16x3_nt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x128_16x3_nt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x64_16x4_nt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x32_16x4_nt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x64_16x4_nt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x32_16x5_nt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_16x32_16x5_nt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x16_16x5_nt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_128x128_16x3_tn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_256x64_16x3_tn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x256_16x3_tn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_256x32_16x3_tn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x256_16x3_tn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_128x64_16x3_tn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x128_16x3_tn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x64_16x4_tn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x32_16x4_tn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x64_16x4_tn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x32_16x5_tn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_16x32_16x5_tn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x16_16x5_tn_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_128x128_16x3_tt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_256x64_16x3_tt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x256_16x3_tt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_256x32_16x3_tt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x256_16x3_tt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_128x64_16x3_tt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x128_16x3_tt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x64_16x4_tt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_64x32_16x4_tt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x64_16x4_tt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x32_16x5_tt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_16x32_16x5_tt_align1(Manifest &manifest);
void initialize_cutlass_tensorop_d884gemm_32x16_16x5_tt_align1(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm80_d884gemm_gemm_operations(Manifest &manifest) {
  initialize_cutlass_tensorop_d884gemm_128x128_16x3_nn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_256x64_16x3_nn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x256_16x3_nn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_256x32_16x3_nn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x256_16x3_nn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_128x64_16x3_nn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x128_16x3_nn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x64_16x4_nn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x32_16x4_nn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x64_16x4_nn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x32_16x5_nn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_16x32_16x5_nn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x16_16x5_nn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_128x128_16x3_nt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_256x64_16x3_nt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x256_16x3_nt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_256x32_16x3_nt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x256_16x3_nt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_128x64_16x3_nt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x128_16x3_nt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x64_16x4_nt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x32_16x4_nt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x64_16x4_nt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x32_16x5_nt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_16x32_16x5_nt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x16_16x5_nt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_128x128_16x3_tn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_256x64_16x3_tn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x256_16x3_tn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_256x32_16x3_tn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x256_16x3_tn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_128x64_16x3_tn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x128_16x3_tn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x64_16x4_tn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x32_16x4_tn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x64_16x4_tn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x32_16x5_tn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_16x32_16x5_tn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x16_16x5_tn_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_128x128_16x3_tt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_256x64_16x3_tt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x256_16x3_tt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_256x32_16x3_tt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x256_16x3_tt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_128x64_16x3_tt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x128_16x3_tt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x64_16x4_tt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_64x32_16x4_tt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x64_16x4_tt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x32_16x5_tt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_16x32_16x5_tt_align1(manifest);
  initialize_cutlass_tensorop_d884gemm_32x16_16x5_tt_align1(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

