
/*
  Generated by rank_k_operation.py - Do not edit.
*/

///////////////////////////////////////////////////////////////////////////////////////////////////
#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

#include "library_internal.h"
#include "rank_k_operation.h"

///////////////////////////////////////////////////////////////////////////////////////////////////


// Rank K operator cutlass_tensorop_s1688syrk_128x128_16x5_n_u_align2
using Operation_cutlass_tensorop_s1688syrk_128x128_16x5_n_u_align2 =
  typename cutlass::gemm::device::RankK<
    float, cutlass::layout::ColumnMajor,
    float, cutlass::layout::ColumnMajor, cutlass::FillMode::kUpper,
    float,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<128, 128, 16>,
    cutlass::gemm::GemmShape<64, 64, 16>,
    cutlass::gemm::GemmShape<16, 8, 8>,
    cutlass::epilogue::thread::LinearCombination<
      float,
      1,
      float,
      float
    >,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
    5,
    2,
    false,
    cutlass::arch::OpMultiplyAddFastF32
>;


///////////////////////////////////////////////////////////////////////////////////////////////////

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_s1688syrk_128x128_16x5_n_u_align2(Manifest &manifest) {



  manifest.append(new RankKOperation<
    Operation_cutlass_tensorop_s1688syrk_128x128_16x5_n_u_align2
  >("cutlass_tensorop_s1688syrk_128x128_16x5_n_u_align2"));



}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

///////////////////////////////////////////////////////////////////////////////////////////////////

