
/*
 Generated by manifest.py - Do not edit.
*/

#include "cutlass/cutlass.h"
#include "cutlass/library/library.h"
#include "cutlass/library/manifest.h"

namespace cutlass {
namespace library {

///////////////////////////////////////////////////////////////////////////////////////////////////

void initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_16x4_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_16x4_nhwc_align2(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_16x4_nhwc_align1(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_16x3_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_16x3_nhwc_align2(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_16x3_nhwc_align1(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_256x64_16x3_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_256x64_16x3_nhwc_align2(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_256x64_16x3_nhwc_align1(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x256_16x3_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x256_16x3_nhwc_align2(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x256_16x3_nhwc_align1(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_128x64_16x4_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_128x64_16x4_nhwc_align2(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_128x64_16x4_nhwc_align1(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x128_16x4_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x128_16x4_nhwc_align2(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x128_16x4_nhwc_align1(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x64_16x3_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x64_16x3_nhwc_align2(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x64_16x3_nhwc_align1(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_32x3_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_32x3_nhwc_align2(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_32x3_nhwc_align1(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_256x64_32x3_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_256x64_32x3_nhwc_align2(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_256x64_32x3_nhwc_align1(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x256_32x3_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x256_32x3_nhwc_align2(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x256_32x3_nhwc_align1(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_128x64_32x3_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_128x64_32x3_nhwc_align2(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_128x64_32x3_nhwc_align1(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x128_32x3_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x128_32x3_nhwc_align2(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x128_32x3_nhwc_align1(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x64_32x3_nhwc_align4(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x64_32x3_nhwc_align2(Manifest &manifest);
void initialize_cutlass_tensorop_s1688wgrad_analytic_64x64_32x3_nhwc_align1(Manifest &manifest);


//
// Entry point to construct operations
//
void initialize_all_sm80_s1688wgrad_analytic_conv2d_operations(Manifest &manifest) {
  initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_16x4_nhwc_align4(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_16x4_nhwc_align2(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_16x4_nhwc_align1(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_16x3_nhwc_align4(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_16x3_nhwc_align2(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_16x3_nhwc_align1(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_256x64_16x3_nhwc_align4(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_256x64_16x3_nhwc_align2(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_256x64_16x3_nhwc_align1(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x256_16x3_nhwc_align4(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x256_16x3_nhwc_align2(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x256_16x3_nhwc_align1(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_128x64_16x4_nhwc_align4(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_128x64_16x4_nhwc_align2(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_128x64_16x4_nhwc_align1(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x128_16x4_nhwc_align4(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x128_16x4_nhwc_align2(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x128_16x4_nhwc_align1(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x64_16x3_nhwc_align4(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x64_16x3_nhwc_align2(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x64_16x3_nhwc_align1(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_32x3_nhwc_align4(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_32x3_nhwc_align2(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_128x128_32x3_nhwc_align1(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_256x64_32x3_nhwc_align4(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_256x64_32x3_nhwc_align2(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_256x64_32x3_nhwc_align1(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x256_32x3_nhwc_align4(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x256_32x3_nhwc_align2(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x256_32x3_nhwc_align1(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_128x64_32x3_nhwc_align4(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_128x64_32x3_nhwc_align2(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_128x64_32x3_nhwc_align1(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x128_32x3_nhwc_align4(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x128_32x3_nhwc_align2(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x128_32x3_nhwc_align1(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x64_32x3_nhwc_align4(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x64_32x3_nhwc_align2(manifest);
  initialize_cutlass_tensorop_s1688wgrad_analytic_64x64_32x3_nhwc_align1(manifest);
}

///////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace library
} // namespace cutlass

